package server;

import java.awt.List;
import java.util.ArrayList;



/**
 * GameMap class definition.
 * Generated by the TouchCORE code generator.
 */
public class GameMap {
    
    private ArrayList<Tile> tiles;
    
    public void partition(Color colors) {
        Village village;
        Tile reachableTiles;
        for (Tile t : tiles) {
            tiles.setColor(colors);
        }
        for (Tile t : tiles) {
            reachableTiles = tiles.reachableTiles();
            if (size of reachableTiles is >= 3) {
                village = new Village(reachableTiles);
            } else {
                
            } else {
                
            }
            if () {
                tiles.setNeutral();
            }
        }
    }

    public static GameMap generateRandomMap() {
        /* TODO: No message view defined */
        return null;
    }

    public Tile getPath(Tile start, Tile end) {
        /* TODO: No message view defined */
        return null;
    }
}
