package server;



/**
 * PaymentManager class definition.
 * Generated by the TouchCORE code generator.
 */
public class PaymentManager {
    
    public static int upgradeCost(UnitType pStart, UnitType pFinish) {
        /* TODO: No message view defined */
        return 0;
    }

    public static int upgradeCost(VillageType oldType, VillageType newType) {
        /* TODO: No message view defined */
        return 0;
    }
}
