package server;

import java.util.ArrayList;



/**
 * Player class definition.
 * Generated by the TouchCORE code generator.
 */
public class Player {
    
    private ArrayList<Village> aVillages;
    private Color myColor;
    
    public void assignColor(Color c) {
        /* TODO: No message view defined */
    }

    public void removeVillage(Village v) {
        /* TODO: No message view defined */
    }

    public Village getVillageRuling(Tile t) {
        /* TODO: No message view defined */
        return null;
    }

    public Village getVillages() {
        /* TODO: No message view defined */
        return null;
    }
}
