package server;

import java.util.ArrayList;



/**
 * Village class definition.
 * Generated by the TouchCORE code generator.
 */
public class Village {
    
    private int aGold;
    private int aWood;
    private VillageType type;
    private int aUpkeepCost;
    private ArrayList<Tile> aTiles;
    private ArrayList<Unit> aUnits;
    private Player myPlayer;
    private Tile myCapital;
    private Region myRegion;
    
    public Village(Tile tiles) {
        /* TODO: No message view defined */
    }

    public void upgradeVillage(VillageType newVillageType) {
        int upgradeCost;
        upgradeCost = PaymentManager.upgradeCost(type, newVillageType);
        if (aWood >= upgradeCost) {
            type = newVillageType;
            aWood -= upgradeCost;
        }
    }

    public void updateTiles() {
        StructureType pStructureType;
        boolean meadow;
        for (Tile lTile : aTiles) {
            pStructureType = lTile.getStructureType();
            if (pStructureType.equals(StructureType.TOMBSTONE)) {
                lTile.setStructureType(StructureType.TREE);
                meadow = lTile.getMeadow();
                if (meadow == true) {
                    aGold += 2;
                } else {
                    aGold += 1;
                }
            }
        }
    }

    public void updateUnits() {
        Unit unit;
        Tile pTile;
        ActionType actionType;
        UnitType aUnitType;
        /*unit = myArrayList.get();  WHAT was this? */
        for (Unit lUnit : aUnits) {
            aUnitType = unit.getUnitType();
            if ((aUnitType.equals(UnitType.PEASANT))) {
                actionType = unit.getActionType();
                if ((actionType.equals(ActionType.CULTIVATING_END)) {
                    pTile = unit.getTile();
                    pTile.setHasMeadow(true);
                    unit.setActionType(actionType.READY); /*have to double check if this should be ready or moved*/
                }
                if ((actionType.equals(ActionType.BUILDINGROAD))) {
                    pTile = unit.getTile();
                    pTile.setStructureType();
                }
            }
        }
    }

    public void addGold(int addGold) {
        /* TODO: No message view defined */
    }

    public void addWood(int addWood) {
        /* TODO: No message view defined */
    }

    public void addTile(Tile newTile) {
        Tile reachableTiles;
        Village village;
        // TODO : adding newTile to the list of Tiles;
        reachableTiles = aTiles.reachableTiles();
        for (Tile t in reachableTiles but not in ruledTiles) {
            village = reachableTiles.getVillage();
            invalid(target);
            reachableTiles = reachableTiles.reachableTiles();
        }
    }

    public void removeTile(Tile t) {
        /* TODO: No message view defined */
    }

    private VillageType getVillageType() {
        /* TODO: No message view defined */
        return null;
    }

    public boolean tryPayingGold(int goldCost) {
        /* TODO: No message view defined */
        return false;
    }

    public Tile getCapital() {
        /* TODO: No message view defined */
        return null;
    }

    public int getAGold() {
        /* TODO: No message view defined */
        return 0;
    }

    public int getAWood() {
        /* TODO: No message view defined */
        return 0;
    }

    public boolean canFuse() {
        if (canFuse) {
            invalid(java.lang.Object@63d2d6fd);
        }
    }

    public void fuse() {
        /* TODO: No message view defined */
    }
}
