package server;

import java.util.ArrayList;



/**
 * Tile class definition.
 * Generated by the TouchCORE code generator.
 */
public class Tile {
    
    private StructureType aStructureType;
    private boolean aHasMeadow;
    private Village myVillage;
    private GameMap myMap;
    private Color myColor;
    private Region myRegion;
    
    public void setColor(Color c) {
        /* TODO: No message view defined */
    }

    public ArrayList<Tile> getReachableTiles() {
        /* TODO: No message view defined */
        return null;
    }

    public void setNeutral() {
        /* TODO: No message view defined */
    }

    public StructureType getStructureType() {
        /* TODO: No message view defined */
        return null;
    }

    public void setStructureType(StructureType aStructureType) {
        /* TODO: No message view defined */
    }

    public boolean getMeadow() {
        /* TODO: No message view defined */
        return false;
    }

    public void setHasMeadow(boolean aHasMeadow) {
        /* TODO: No message view defined */
    }

    public Village getVillage() {
        /* TODO: No message view defined */
        return null;
    }

    public void setVillage(Village v) {
        /* TODO: No message view defined */
    }
}
