package server;

/**
 * StructureType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum StructureType {
    TREE,
    TOMBSTONE,
    ROAD,
    NO_STRUCT,
    VILLAGE,
    WATCHTOWER
}
