package mw.server.gamelogic.model;

/**
 * ActionType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum ActionType {
    BUILDINGROAD,
    CHOPPINGTREE,
    CULTIVATING_BEGIN,
    CULTIVATING_END,  //TODO: check if we need both cultivate end and cultivate beginning, based on that 
    					//change the updateUnits function in Village.java
    READY,
    MOVED;
}
