package mw.server.gamelogic.model;

import java.io.Serializable;

/**
 * VillageType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum VillageType implements Serializable{
	NO_VILLAGE,
    HOVEL,
    TOWN,
    FORT

}