package mw.server.gamelogic;

/**
 * ActionType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum ActionType {
    BUILDINGROAD,
    CHOPPINGTREE,
    CULTIVATING_BEGIN,
    CULTIVATING_END,
    READY,
    MOVED
}
