package mw.server.gamelogic;




/**
 * MapBase class definition.
 * Generated by the TouchCORE code generator.
 */
public class MapBase {
    
   // private Map<Integer, GameMap> myMap;
   // private static MapBase singleton;
    
    public static GameMap getMap(int mapID) {
        /* TODO: No message view defined */
        return null;
    }

    public static MapBase singleton() {
        /* TODO: No message view defined */
        return null;
    }
}
