package mw.server.gamelogic;


import java.util.Collection;



/**
 * Player class definition.
 * Generated by the TouchCORE code generator.
 */
public class Player {

	private Color aColor; 
    private Collection<Village> aVillages;
	
	public Player ()
	{
		
	}
	
    public void assignColor(Color pColor)
    {
      aColor = pColor; 
    }
    
    public Color getPlayerColor()
    {
    	return aColor; 
    }

    public void removeVillage(Village pVillage) 
    {
        aVillages.remove(pVillage); 
    }

    public Collection<Village> getVillages() 
    {
    	return aVillages; 
    }
}
