package mw.server.gamelogic;


import java.util.Collection;



/**
 * Player class definition.
 * Generated by the TouchCORE code generator.
 */
public class Player {
	
	private int id; 
	private Color aColor; 
    private Collection<Village> aVillages;
	
	public Player (int pId)
	{
		id = pId;	
	}
	
    public void assignColor(Color pColor)
    {
      aColor = pColor; 
    }
    
    public Color getPlayerColor()
    {
    	return aColor; 
    }
    
    public int getPlayerID()
    {
    	return id; 
    }

    public void removeVillage(Village pVillage) 
    {
        aVillages.remove(pVillage); 
    }

    public Collection<Village> getVillages() 
    {
    	return aVillages; 
    }
}
