package mw.server.gamelogic;

import java.util.ArrayList;



/**
 * Region class definition.
 * Generated by the TouchCORE code generator.
 */
public class Region {
    
    private Village myVillage;
    private ArrayList<Tile> myTile;
    
    public void addTile(Tile t) {
        /* TODO: No message view defined */
    }
}
