package mw.server.gamelogic;

import java.io.Serializable;

/**
 * StructureType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum StructureType implements Serializable{
    TREE,
    TOMBSTONE,
    ROAD,
    NO_STRUCT,
    VILLAGE_CAPITAL,
    WATCHTOWER
}
