package mw.server.gamelogic;
/**
 * StructureType enumeration definition.
 * Generated by the TouchCORE code generator.
 */
public enum StructureType {
    TREE,
    TOMBSTONE,
    ROAD,
    NO_STRUCT,
    VILLAGE_CAPITAL,
    WATCHTOWER
}
