package mw.server.gamelogic;

import java.util.ArrayList;



/**
 * Tile class definition.
 * Generated by the TouchCORE code generator.
 */
public class Tile {
    

    private StructureType aStructureType; 
    private Unit aUnit; 
    private boolean aHasMeadow;
    private GameMap aMap;
    private final int aX;
    private final int aY;
    private Color myColor;
    private ArrayList<Tile> aNeighbors; 
   
    
    public Tile(StructureType pStructureType, int pX, int pY) 
    { 
    	aX= pX; 
    	aY = pY; 
    	aStructureType = pStructureType; 
    	myColor = Color.NEUTRAL;
    	aHasMeadow = false; 
    }
    
    public void initializeNeighbors(ArrayList<Tile> pNeighbors)
    {
    	aNeighbors = pNeighbors; 
    }
    public void setColor(Color c) {
       myColor = c; 
    }


    public void setNeutral() {
        myColor = Color.NEUTRAL; 
    }

    public StructureType getStructureType() {
       return aStructureType;
    }

    public void setStructureType(StructureType pStructureType) {
        pStructureType = aStructureType; 
    }

    public boolean getMeadow() {
      
        return aHasMeadow; 
    }

    public void setHasMeadow(boolean pHasMeadow) {
       aHasMeadow = pHasMeadow; 
    }

    public Color getColor() {
        return myColor; 
    }

	public Unit getUnit() 
	{
		return aUnit; 
	}
	public void setUnit(Unit pUnit)
	{
		aUnit = pUnit; 
	}
	public boolean isProtected(UnitType pType)
	{
		return false; 
	}
	public Village getVillage()
	{
		 Village myVillage = new Village(aMap.getSameColorTiles(this));
		 return myVillage; 
	}

	public void setVillage(Village invadingVillage) {
		// TODO Auto-generated method stub
		
	}

	public int[] getCoordinates() {
		int [] toRet = {aX, aY};
		return toRet; 
		
	}
}
