package server;



/**
 * TypesLogic class definition.
 * Generated by the TouchCORE code generator.
 */
public class TypesLogic {
    
    public static boolean greaterThan(VillageType a, VillageType b) {
        /* TODO: No message view defined */
        return false;
    }
}
