package mw.server.gamelogic;

import java.io.Serializable;



/**
 * Unit class definition.
 * Generated by the TouchCORE code generator.
 */
public class Unit implements Serializable{
    
	private UnitType aUnitType;
    private ActionType aActionType;
    public Unit( UnitType pUnitType)
    {
    	aUnitType = pUnitType; 
    }
    
    /**
     * 
     * @param pUnitType 
     * Updates the unitType
     */
    public void setUnitType(UnitType pUnitType) {
        /* TODO: No message view defined */
    }

    /**
     * 
     * @return unitType
     */
    public UnitType getUnitType() {
        /* TODO: No message view defined */
        return null;
    }

    public ActionType getActionType() {
        /* TODO: No message view defined */
        return null;
    }

    public void setActionType(ActionType aActionType) {
        /* TODO: No message view defined */
    }

   
}
