package mw.server.gamelogic;

/**
 * UnitType enumeration definition.
 * Generated by the TouchCORE code generator.
 * 
 * KEEP THEM IN THIS ORDER OR DIE
 */
public enum UnitType {
	 PEASANT,
	INFANTRY,
    SOLDIER,
    KNIGHT,
	 NO_UNIT; 
}
