package mw.server.gamelogic;



/**
 * Unit class definition.
 * Generated by the TouchCORE code generator.
 */
public class Unit {
    
    private UnitType aUnitType;
    private ActionType aActionType;
    private Tile myTile;
    
    /**
     * 
     * @param pUnitType 
     * Updates the unitType
     */
    public void setUnitType(UnitType pUnitType) {
        /* TODO: No message view defined */
    }

    /**
     * 
     * @return unitType
     */
    public UnitType getUnitType() {
        /* TODO: No message view defined */
        return null;
    }

    public ActionType getActionType() {
        /* TODO: No message view defined */
        return null;
    }

    public void setActionType(ActionType aActionType) {
        /* TODO: No message view defined */
    }

    public Tile getTile() {
        /* TODO: No message view defined */
        return null;
    }

    public void setTile(Tile newTile) {
        /* TODO: No message view defined */
    }
}
