package mw.server.gamelogic;

import java.io.Serializable;
import java.util.ArrayList;



/**
 * Village class definition.
 * Generated by the TouchCORE code generator.
 */
public class Village implements Cloneable, Serializable{
    
    /*
     * absolutely necessary Village attributes
     */
	private int aGold; 
    private int aWood;  
    private VillageType aVillageType;
    private int aUpkeepCost;
    private ArrayList<Tile> aTiles;
    private Tile myCapital;
    private GameMap aMap;
    /*
     * Village attributes that I want to remove 
     */
    private ArrayList<Unit> aUnits; //figure out a way to factor this out of village 
    
    
    
    
    public Village(ArrayList<Tile> pTiles) {
        /* TODO: No message view defined */
    }

    public void upgradeVillage(VillageType newVillageType) throws NotEnoughIncomeException {
        int upgradeCost;
        upgradeCost = PaymentManager.upgradeCost(aVillageType, newVillageType);
        if (aWood >= upgradeCost) {
            aVillageType = newVillageType;
            aWood -= upgradeCost;
        }
        else 
        {
        	throw new NotEnoughIncomeException(aGold - upgradeCost); 
        }
    }

    public void updateTiles() {
        StructureType pStructureType;
        boolean meadow;
        for (Tile lTile : aTiles) {
            pStructureType = lTile.getStructureType();
            if (pStructureType.equals(StructureType.TOMBSTONE)) {
                lTile.setStructureType(StructureType.TREE);
                meadow = lTile.getMeadow();
                if (meadow == true) {
                    aGold += 2;
                } else {
                    aGold += 1;
                }
            }
        }
    }

    public void updateUnits()  {
        Tile pTile;
        ActionType actionType;
        UnitType aUnitType;
        for (Unit lUnit : aUnits) {
            aUnitType = lUnit.getUnitType();
            if ((aUnitType.equals(UnitType.PEASANT))) {
                actionType = lUnit.getActionType();
                if ((actionType.equals(ActionType.CULTIVATING_END))) {
                    pTile = lUnit.getTile();
                    pTile.setHasMeadow(true);
                    lUnit.setActionType(actionType.READY); /*have to double check if this should be ready or moved*/
                }
                if ((actionType.equals(ActionType.BUILDINGROAD))) {
                    pTile = lUnit.getTile();
                    pTile.setStructureType(StructureType.ROAD);
                }
            }
        }
    }

    /**
     * Adds the specified amount of gold to the village
     * @param addGold
     */
    public void addGold(int addGold) 
    {
        aGold+=addGold; 
    }

    /**
     * Adds the specified amount of wood to the village
     * @param addWood
     */
    public void addWood(int addWood) 
    {
       aWood += addWood; 
    }

    
  /**
   * add a specified Tile to a village, then check if adding that tile caused 
   * two villages under the same player to become one Mega-Village
   * ONLY called either after removeTile from an enemy village, or on neutral land 
   * @param pTile
   */
    public void addTile(Tile pTile) {
    	ArrayList<Village> fusableVillages; 
    	aTiles.add(pTile);
    	fusableVillages = aMap.getNeighboringVillages(pTile); 
    	for (Village lVillage : fusableVillages)
    	{
    		if (aMap.canFuse(lVillage, this))
    		{
    			aMap.fuseVillages(lVillage, this);
    		}
    	}
    }

    public void removeTile(Tile t) {
        /* TODO: No message view defined */
    }

    public VillageType getVillageType() 
    {
    	return aVillageType; 
    }

    /**
     * checks if there's enough gold to pay all villagers 
     * if there is then village gold is reduced by the cost
     * otherwise a NotEnoughIncomeException is thrown and dealt with in the calling class 
     * @param goldCost
     * @throws NotEnoughIncomeException
     */
    public void tryPayingGold(int goldCost) throws NotEnoughIncomeException {
        if (aGold >= goldCost)
        {
        	aGold = aGold - goldCost; 
        }
        else 
        {
        	throw new NotEnoughIncomeException((aGold-goldCost)); 
        }
    }

    public Tile getCapital() {
        /* TODO: No message view defined */
        return null;
    }

    /**
     * getter for Village Gold
     * @return
     */
    public int getAGold() 
    {
        
        return aGold;
    }

    /**
     * getter for Village Wood
     * @return
     */
    public int getAWood() 
    {
      return aWood;
    }

    /**
     * This method should ONLY be called for getting equality
     * @return
     */
	public ArrayList<Tile> getTiles() {  
		// TODO Auto-generated method stub
		return (ArrayList<Tile>) aTiles.clone(); 
	}

	


    
    
}
